import json
import os

langs = {
    "en_us": {
        "mod.androidopt.name": "Android Optimizer",
        "mod.androidopt.description": "Optimizes Minecraft for Android ARM64 (Amethyst / PojavLauncher).\nReduces GC freezes, disables useless rendering, aggressively frees memory to double/triple FPS on mobile.\nInactive on PC — automatic detection.\nIncludes: adaptive frame budget, BER culling, chunk rebuild throttle, ARM big.LITTLE thread affinity.",
        "androidopt.page.home": "Home",
        "androidopt.page.render": "Render & FPS",
        "androidopt.page.memory": "Memory & RAM",
        "androidopt.page.create": "Create & Flywheel",
        "androidopt.page.sound": "Sound",
        "androidopt.page.world": "World & Entities",
        "androidopt.page.soc": "SoC Profile",
        "androidopt.page.diag": "Debug & HUD",
        "androidopt.config.force_pc": "Force on PC (test)",
        "androidopt.config.render_opts": "Reduced rendering at startup",
        "androidopt.config.disable_clouds": "Disable clouds",
        "androidopt.config.disable_ao": "Disable AO",
        "androidopt.config.disable_entity_shadows": "Disable entity shadows",
        "androidopt.config.minimal_particles": "Minimal particles",
        "androidopt.config.create_particles_filter": "Filter Create particles",
        "androidopt.config.render_scale": "Render scale 75% (+40% FPS)",
        "androidopt.config.show_hud": "Show HUD",
        "androidopt.config.memory_watchdog": "Memory monitoring (GC)",
        "androidopt.config.texture_cache_evictor": "Texture cache eviction",
        "androidopt.config.section_buffer_limit": "Limit chunk buffers (4)",
        "androidopt.config.ponder_cache_clear": "Clear Ponder Create cache",
        "androidopt.config.max_total_ram": "Total RAM budget (MB)",
        "androidopt.config.gc_threshold": "GC threshold (%)",
        "androidopt.config.create_ber_culler": "Create BER culler (>16 blocks)",
        "androidopt.config.chunk_rebuild_throttler": "Chunk rebuild throttle",
        "androidopt.config.flywheel_buffer_culler": "Flywheel buffers (culler)",
        "androidopt.config.flywheel_backend_force": "Flywheel Instancing backend",
        "androidopt.config.stopped_contraption_skip": "Skip stopped contraptions",
        "androidopt.config.fluid_render_culler": "Create fluids (>12 blocks)",
        "androidopt.config.goggle_overlays": "Goggle overlays (>8 blocks)",
        "androidopt.config.kinetic_network_skip": "Kinetic network (solo)",
        "androidopt.config.create_render_fps": "Create render FPS",
        "androidopt.config.chunk_rebuilds_per_frame": "Chunk rebuilds/frame",
        "androidopt.config.ambient_sound_suppressor": "Ambient sounds OFF",
        "androidopt.config.weather_suppressor": "Suppress weather",
        "androidopt.config.entity_throttler": "Throttle distant entities",
        "androidopt.config.tick_skipper": "Tick skipper (distant BEs)",
        "androidopt.config.chunk_unloader": "Unload chunks",
        "androidopt.config.server_be_tick_throttle": "Server BE ticks (solo ÷4)",
        "androidopt.config.auto_apply_soc_profile": "Auto-apply profile at startup",
        "androidopt.config.freeze_debugger": "FreezeDebugger (logs)",
        "androidopt.config.debug_verbose_log": "Detailed logs (verbose)",
        "androidopt.config.hud_show_fps": "Show FPS",
        "androidopt.config.hud_show_heap": "Show Heap/RAM",
        "androidopt.config.hud_show_budget": "Show Frame Budget",
        "androidopt.config.hud_show_soc": "Show SoC + Mode",
        "androidopt.config.hud_show_optims": "Show optim states",
        "androidopt.config.hud_show_freeze": "Show Freeze stats",
        "androidopt.config.fps_limit": "Global max FPS",
        "androidopt.config.render_distance": "Render distance (chunks)",
        "androidopt.config.mipmap_levels": "Mipmap levels"
    },
    "fr_fr": {
        "mod.androidopt.name": "Android Optimizer",
        "mod.androidopt.description": "Optimise Minecraft pour Android ARM64 (Amethyst / PojavLauncher).\nRéduit les freezes GC, désactive le rendu inutile, libère la mémoire agressivement pour doubler/tripler les FPS sur mobile.\nInactif sur PC — détection automatique.\nInclut : frame budget adaptatif, BER culling, chunk rebuild throttle, thread affinity ARM big.LITTLE.",
        "androidopt.page.home": "Accueil",
        "androidopt.page.render": "Rendu & FPS",
        "androidopt.page.memory": "Mémoire & RAM",
        "androidopt.page.create": "Create & Flywheel",
        "androidopt.page.sound": "Son",
        "androidopt.page.world": "Monde & Entités",
        "androidopt.page.soc": "Profil SoC",
        "androidopt.page.diag": "Diagnostic & HUD",
        "androidopt.config.force_pc": "Forcer sur PC (test)",
        "androidopt.config.render_opts": "Rendu réduit au démarrage",
        "androidopt.config.disable_clouds": "Désactiver nuages",
        "androidopt.config.disable_ao": "Désactiver AO",
        "androidopt.config.disable_entity_shadows": "Désactiver ombres entités",
        "androidopt.config.minimal_particles": "Particules minimales",
        "androidopt.config.create_particles_filter": "Filtrer particules Create",
        "androidopt.config.render_scale": "Render scale 75% (+40% FPS)",
        "androidopt.config.show_hud": "Afficher HUD",
        "androidopt.config.memory_watchdog": "Surveillance mémoire (GC)",
        "androidopt.config.texture_cache_evictor": "Éviction cache textures",
        "androidopt.config.section_buffer_limit": "Limiter buffers chunks (4)",
        "androidopt.config.ponder_cache_clear": "Vider cache Ponder Create",
        "androidopt.config.max_total_ram": "Budget RAM total (Mo)",
        "androidopt.config.gc_threshold": "Seuil GC (%)",
        "androidopt.config.create_ber_culler": "BER culler Create (>16 blocs)",
        "androidopt.config.chunk_rebuild_throttler": "Chunk rebuild throttle",
        "androidopt.config.flywheel_buffer_culler": "Buffers Flywheel (culler)",
        "androidopt.config.flywheel_backend_force": "Backend Flywheel Instancing",
        "androidopt.config.stopped_contraption_skip": "Skip contraptions arrêtées",
        "androidopt.config.fluid_render_culler": "Fluides Create (>12 blocs)",
        "androidopt.config.goggle_overlays": "Goggle overlays (>8 blocs)",
        "androidopt.config.kinetic_network_skip": "Réseau cinétique (solo)",
        "androidopt.config.create_render_fps": "FPS rendu Create",
        "androidopt.config.chunk_rebuilds_per_frame": "Rebuilds chunks/frame",
        "androidopt.config.ambient_sound_suppressor": "Sons ambiants OFF",
        "androidopt.config.weather_suppressor": "Supprimer météo",
        "androidopt.config.entity_throttler": "Throttle entités lointaines",
        "androidopt.config.tick_skipper": "Tick skipper (BEs lointains)",
        "androidopt.config.chunk_unloader": "Décharger chunks",
        "androidopt.config.server_be_tick_throttle": "Tick BEs serveur (solo ÷4)",
        "androidopt.config.auto_apply_soc_profile": "Appliquer profil auto au démarrage",
        "androidopt.config.freeze_debugger": "FreezeDebugger (logs)",
        "androidopt.config.debug_verbose_log": "Logs détaillés (verbose)",
        "androidopt.config.hud_show_fps": "Afficher FPS",
        "androidopt.config.hud_show_heap": "Afficher Heap/RAM",
        "androidopt.config.hud_show_budget": "Afficher Budget frame",
        "androidopt.config.hud_show_soc": "Afficher SoC + Mode",
        "androidopt.config.hud_show_optims": "Afficher états optims",
        "androidopt.config.hud_show_freeze": "Afficher stats Freeze",
        "androidopt.config.fps_limit": "FPS max global",
        "androidopt.config.render_distance": "Render distance (chunks)",
        "androidopt.config.mipmap_levels": "Mipmap levels"
    },
    "de_de": {
        "mod.androidopt.name": "Android Optimizer",
        "mod.androidopt.description": "Optimiert Minecraft für Android ARM64 (Amethyst / PojavLauncher).\nReduziert GC-Freezes, deaktiviert nutzloses Rendering, gibt Speicher aggressiv frei, um die FPS auf Mobilgeräten zu verdoppeln/verdreifachen.\nAuf dem PC inaktiv – automatische Erkennung.\nEnthält: adaptives Frame-Budget, BER-Culling, Chunk-Rebuild-Drosselung, ARM big.LITTLE Thread-Affinität.",
        "androidopt.page.home": "Startseite",
        "androidopt.page.render": "Rendern & FPS",
        "androidopt.page.memory": "Speicher & RAM",
        "androidopt.page.create": "Create & Flywheel",
        "androidopt.page.sound": "Ton",
        "androidopt.page.world": "Welt & Entitäten",
        "androidopt.page.soc": "SoC-Profil",
        "androidopt.page.diag": "Debug & HUD",
        "androidopt.config.force_pc": "Auf PC erzwingen (Test)",
        "androidopt.config.render_opts": "Reduziertes Rendering beim Start",
        "androidopt.config.disable_clouds": "Wolken deaktivieren",
        "androidopt.config.disable_ao": "AO deaktivieren",
        "androidopt.config.disable_entity_shadows": "Entitätsschatten deaktivieren",
        "androidopt.config.minimal_particles": "Minimale Partikel",
        "androidopt.config.create_particles_filter": "Create-Partikel filtern",
        "androidopt.config.render_scale": "Render-Skalierung 75% (+40% FPS)",
        "androidopt.config.show_hud": "HUD anzeigen",
        "androidopt.config.memory_watchdog": "Speicherüberwachung (GC)",
        "androidopt.config.texture_cache_evictor": "Textur-Cache leeren",
        "androidopt.config.section_buffer_limit": "Chunk-Puffer begrenzen (4)",
        "androidopt.config.ponder_cache_clear": "Ponder Create-Cache leeren",
        "androidopt.config.max_total_ram": "Gesamtes RAM-Budget (MB)",
        "androidopt.config.gc_threshold": "GC-Schwellenwert (%)",
        "androidopt.config.create_ber_culler": "Create BER-Culler (>16 Blöcke)",
        "androidopt.config.chunk_rebuild_throttler": "Chunk-Rebuild-Drosselung",
        "androidopt.config.flywheel_buffer_culler": "Flywheel-Puffer (Culler)",
        "androidopt.config.flywheel_backend_force": "Flywheel Instancing Backend",
        "androidopt.config.stopped_contraption_skip": "Gestoppte Contraptions überspringen",
        "androidopt.config.fluid_render_culler": "Create-Flüssigkeiten (>12 Blöcke)",
        "androidopt.config.goggle_overlays": "Goggle-Overlays (>8 Blöcke)",
        "androidopt.config.kinetic_network_skip": "Kinetisches Netzwerk (solo)",
        "androidopt.config.create_render_fps": "Create-Render-FPS",
        "androidopt.config.chunk_rebuilds_per_frame": "Chunk-Rebuilds/Frame",
        "androidopt.config.ambient_sound_suppressor": "Umgebungsgeräusche AUS",
        "androidopt.config.weather_suppressor": "Wetter unterdrücken",
        "androidopt.config.entity_throttler": "Entfernte Entitäten drosseln",
        "androidopt.config.tick_skipper": "Tick-Skipper (entfernte BEs)",
        "androidopt.config.chunk_unloader": "Chunks entladen",
        "androidopt.config.server_be_tick_throttle": "Server-BE-Ticks (solo ÷4)",
        "androidopt.config.auto_apply_soc_profile": "Profil beim Start automatisch anwenden",
        "androidopt.config.freeze_debugger": "FreezeDebugger (Logs)",
        "androidopt.config.debug_verbose_log": "Detaillierte Logs (ausführlich)",
        "androidopt.config.hud_show_fps": "FPS anzeigen",
        "androidopt.config.hud_show_heap": "Heap/RAM anzeigen",
        "androidopt.config.hud_show_budget": "Frame-Budget anzeigen",
        "androidopt.config.hud_show_soc": "SoC + Modus anzeigen",
        "androidopt.config.hud_show_optims": "Optimierungsstatus anzeigen",
        "androidopt.config.hud_show_freeze": "Freeze-Statistiken anzeigen",
        "androidopt.config.fps_limit": "Globales max. FPS",
        "androidopt.config.render_distance": "Sichtweite (Chunks)",
        "androidopt.config.mipmap_levels": "Mipmap-Level"
    },
    "es_es": {
        "mod.androidopt.name": "Android Optimizer",
        "mod.androidopt.description": "Optimiza Minecraft para Android ARM64 (Amethyst / PojavLauncher).\nReduce los congelamientos del GC, desactiva el renderizado inútil, libera memoria agresivamente para duplicar/triplicar los FPS en móviles.\nInactivo en PC — detección automática.\nIncluye: presupuesto de fotogramas adaptativo, culling de BER, limitador de reconstrucción de chunks, afinidad de subprocesos ARM big.LITTLE.",
        "androidopt.page.home": "Inicio",
        "androidopt.page.render": "Renderizado y FPS",
        "androidopt.page.memory": "Memoria y RAM",
        "androidopt.page.create": "Create y Flywheel",
        "androidopt.page.sound": "Sonido",
        "androidopt.page.world": "Mundo y Entidades",
        "androidopt.page.soc": "Perfil SoC",
        "androidopt.page.diag": "Diagnóstico y HUD",
        "androidopt.config.force_pc": "Forzar en PC (prueba)",
        "androidopt.config.render_opts": "Renderizado reducido al inicio",
        "androidopt.config.disable_clouds": "Desactivar nubes",
        "androidopt.config.disable_ao": "Desactivar AO",
        "androidopt.config.disable_entity_shadows": "Desactivar sombras de entidades",
        "androidopt.config.minimal_particles": "Partículas mínimas",
        "androidopt.config.create_particles_filter": "Filtrar partículas de Create",
        "androidopt.config.render_scale": "Escala de renderizado 75% (+40% FPS)",
        "androidopt.config.show_hud": "Mostrar HUD",
        "androidopt.config.memory_watchdog": "Monitorización de memoria (GC)",
        "androidopt.config.texture_cache_evictor": "Desalojo de caché de texturas",
        "androidopt.config.section_buffer_limit": "Limitar búferes de chunks (4)",
        "androidopt.config.ponder_cache_clear": "Borrar caché de Ponder de Create",
        "androidopt.config.max_total_ram": "Presupuesto total de RAM (MB)",
        "androidopt.config.gc_threshold": "Umbral de GC (%)",
        "androidopt.config.create_ber_culler": "Culler BER de Create (>16 bloques)",
        "androidopt.config.chunk_rebuild_throttler": "Límite de reconstrucción de chunks",
        "androidopt.config.flywheel_buffer_culler": "Búferes de Flywheel (culler)",
        "androidopt.config.flywheel_backend_force": "Backend de Instancing de Flywheel",
        "androidopt.config.stopped_contraption_skip": "Omitir contraptions detenidas",
        "androidopt.config.fluid_render_culler": "Fluidos de Create (>12 bloques)",
        "androidopt.config.goggle_overlays": "Superposiciones de Goggles (>8 bloques)",
        "androidopt.config.kinetic_network_skip": "Red cinética (solo)",
        "androidopt.config.create_render_fps": "FPS de renderizado de Create",
        "androidopt.config.chunk_rebuilds_per_frame": "Reconstrucciones de chunks/fotograma",
        "androidopt.config.ambient_sound_suppressor": "Sonidos ambientales OFF",
        "androidopt.config.weather_suppressor": "Suprimir el clima",
        "androidopt.config.entity_throttler": "Limitar entidades distantes",
        "androidopt.config.tick_skipper": "Omisor de ticks (BE distantes)",
        "androidopt.config.chunk_unloader": "Descargar chunks",
        "androidopt.config.server_be_tick_throttle": "Ticks de BE del servidor (solo ÷4)",
        "androidopt.config.auto_apply_soc_profile": "Aplicar perfil auto al inicio",
        "androidopt.config.freeze_debugger": "FreezeDebugger (logs)",
        "androidopt.config.debug_verbose_log": "Logs detallados (verbose)",
        "androidopt.config.hud_show_fps": "Mostrar FPS",
        "androidopt.config.hud_show_heap": "Mostrar Heap/RAM",
        "androidopt.config.hud_show_budget": "Mostrar Presupuesto de Fotogramas",
        "androidopt.config.hud_show_soc": "Mostrar SoC + Modo",
        "androidopt.config.hud_show_optims": "Mostrar estados de optimizaciones",
        "androidopt.config.hud_show_freeze": "Mostrar estadísticas de Freeze",
        "androidopt.config.fps_limit": "Límite global de FPS",
        "androidopt.config.render_distance": "Distancia de renderizado (chunks)",
        "androidopt.config.mipmap_levels": "Niveles de mipmap"
    }
}

for lang_code, translations in langs.items():
    file_path = f"/home/ubuntu/android-optimizer/src/main/resources/assets/androidopt/lang/{lang_code}.json"
    with open(file_path, "w", encoding="utf-8") as f:
        json.dump(translations, f, indent=2, ensure_ascii=False)

print("Language files successfully generated.")
